In [2]:
import numpy as np
import networkx 
from networkx import karate_club_graph, to_numpy_matrix

In [15]:
#Adjacency Matrix
A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1], 
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float
)

#Identity Matrix of the same shape as A
I = np.matrix(np.eye(A.shape[0]))

A_hat = A+I

#Degree matrix
D = np.array(np.sum(A_hat, axis=0))[0]
D = np.matrix(np.diag(D))

#nodes features
#shape = 4 (nodes), 2 (num of features)
X = np.matrix([
    [i, -i]
    for i in range(A.shape[0])
], dtype=float)

#weights
#shape = 2 (number of input features), 3 (number of output features)
W = np.matrix([
     [1, -0.9, 0.7],
     [-1, 0.5, 0.5]
])

#linear activation
#shape = 4 (nodes), 3 (num of output features from W)
y = D**-1 * A_hat * X * W

#relu
y[y<0]=0

print('X\n',X)
print('Y\n',y)

X
 [[ 0.  0.]
 [ 1. -1.]
 [ 2. -2.]
 [ 3. -3.]]
Y
 [[1.  0.  0.1]
 [4.  0.  0.4]
 [2.  0.  0.2]
 [5.  0.  0.5]]


In [29]:
print(D**-1 * A_hat * X,'\n\n', W, '\n\n', D**-1 * A_hat * X * W)

[[ 0.5 -0.5]
 [ 2.  -2. ]
 [ 1.  -1. ]
 [ 2.5 -2.5]] 

 [[ 1.  -0.9  0.7]
 [-1.   0.5  0.5]] 

 [[ 1.  -0.7  0.1]
 [ 4.  -2.8  0.4]
 [ 2.  -1.4  0.2]
 [ 5.  -3.5  0.5]]


In [22]:
def GCN_forward(A, X, W):
    I = np.matrix(np.eye(A.shape[0]))
    A_hat = A+I
    D = np.array(np.sum(A_hat, axis=0))[0]
    D = np.matrix(np.diag(D))
    y = D**-1 * A_hat * X * W
    y[y<0]=0
    return y

In [23]:
GCN_forward(A, X, W)

matrix([[1. , 0. , 0.1],
        [4. , 0. , 0.4],
        [2. , 0. , 0.2],
        [5. , 0. , 0.5]])

In [24]:
y

matrix([[1. , 0. , 0.1],
        [4. , 0. , 0.4],
        [2. , 0. , 0.2],
        [5. , 0. , 0.5]])